#development:
#  adapter: mysql2
#  encoding: utf8
#  pool: 10
#  username: root
#  password:
#  database: Kicker_development
#  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: fhspost-kicker
  password: 82koeJup7pxNBetG8aK3krfhCDViWnnwLpazBWx2T2bf962AWJ
  database: fhspost_prod
  host: 173.194.246.9

production:
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>