development:
  adapter: mysql2
  encoding: utf8
  pool: 20
  username: root
  password:
  database: Kicker_development
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 20
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>